variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  SPRING_PROFILES_ACTIVE: "ci"

image: maven:latest

stages:
  - build
  - test
  - package
  - deploy

cache:
  paths:
    - .m2/repository


build_job:
  stage: build

  script:
    - mvn compile

test_job:
  stage: test

  script:
    - mvn -B -U clean test

package_job:
  stage: package

  script:
    - mvn package

