volumes:
  pg_bank:


services:

  redis:
    ports:
      - "6379:6379"
    image: redis:7
    container_name: redis_bank
    restart: always
    command: ["redis-server", "--appendonly", "yes"]


  bank_db:
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: bank_db

    volumes:
      - pg_bank:/var/lib/postgresql/data

    ports:
      - "127.0.0.1:5433:5432"

  app:
    restart: always
    build: .
    ports:
      - "8080:8080"

    depends_on:
      - bank_db
      - redis

    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://bank_db:5432/bank_db'
      JAVA_OPTS: '-Xmx512m'



