

spring:

  liquibase:
    enabled: true
    change-log: classpath:/db/migration/db.changelog-master.xml
    contexts: dev


  profiles:
    active: dev



  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: false

    show-sql: false
    generate-ddl: false


